### ISSUE TITLE
sAMAccountName

### ISSUE THREAD

**Issue by markiceman** [davidmehren/maubot-ldap-inviter#5]
We don't using uid. We using sAMAccountName for mxids. Please, make this parameter configurable.

Thank You very much.

**Comment by davidmehren** [comment]
I'm happy to merge pull requests for this, but will not actively implement feature requests, as the current state of the plugin fits my use-case.

**Comment by markiceman** [comment]
OK, I understand.

I changed uid -> saAMAaccountname in code. ldap-check works, but ldap-sync:

Traceback (most recent call last):
  File "/data/plugins/de.herrmehren.ldap-inviter-v0.0.1.mbp/inviter/[bot.py](http://bot.py/)", line 104, in ldap_sync
    await self.sync_rooms(evt, self.config["sync_rooms"], template_arg)
  File "/data/plugins/de.herrmehren.ldap-inviter-v0.0.1.mbp/inviter/[bot.py](http://bot.py/)", line 90, in sync_rooms
    await self.sync_room(evt, room, template_arg1)
  File "/data/plugins/de.herrmehren.ldap-inviter-v0.0.1.mbp/inviter/[bot.py](http://bot.py/)", line 56, in sync_room
    room_id = await self.matrix_utils.ensure_room_with_alias(alias)
  File "/data/plugins/de.herrmehren.ldap-inviter-v0.0.1.mbp/inviter/matrix_[utils.py](http://utils.py/)", line 70, in ensure_room_with_alias
    room = await [self.room](http://self.room/)_methods.get_room_alias(alias)
AttributeError: 'RoomMethods' object has no attribute 'get_room_alias'

Do you have any idea?
